### ISSUE TITLE
Use github actions to create binaries

### ISSUE THREAD

**Issue by KatrionaGoldmann** [alan-turing-institute/whatwhat#97]

**Comment by yongrenjie** [comment]
As we discovered, this can't be easily done because GitHub Actions doesn't have M1 runners.

The alternative would be to cross-compile, but that's one for the future...!

**Comment by yongrenjie** [comment]
GitHub Actions _does_ have M1 runners now, but they cost money (even for the ATI organisation!) I accidentally charged the Turing £7.50 by testing out the runners before discovering this 🥲

The current solution is to build the binaries locally on anyone's M1 Mac. This is now automated in [`bin/update.ml`](https://github.com/alan-turing-institute/whatwhat/blob/main/bin/update.ml). The code could be a lot better but it works(!) So, running `dune exec update_whatwhat` will handle the entire update process incl. building the bottle, uploading the bottle to a new release, and updating the Homebrew tap 🙂

This is probably the best we can do until they make M1 runners free, so I think we can consider this completed, and revisit it in the future if needed. (And the nice thing is that if they ever make it free, the GitHub Action can simply consist of checking out the repository and running `dune exec update_whatwhat`)
