### ISSUE TITLE
Add whatwhat init command to populate config files

### ISSUE THREAD

**Issue by KatrionaGoldmann** [alan-turing-institute/whatwhat#98]

**Comment by IFenton** [comment]
Approximate layout for the function:

Check whether config files exists

if they exist:
    1. ask if user wants the config files printed
    2. print out config files (if requested)
if they don't:
    1. give basic examples of config files to be filled in
    2. create config files in the correct folders
    3. check if they exist

**Comment by KatrionaGoldmann** [comment]
Done in #102
